# Generated by Django 5.1.1 on 2024-09-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity_value', models.FloatField()),
                ('measurement_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Illumination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_level', models.FloatField()),
                ('measurement_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_value', models.FloatField()),
                ('measurement_time', models.DateTimeField()),
                ('unit', models.CharField(max_length=64)),
            ],
        ),
    ]
